services:
  frontend:
    container_name: blog-frontend
    image: node:hydrogen-bullseye-slim
    user: node
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/workspace:cached
    working_dir: /workspace
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
